version: "3.7"

services: 

    pyapp1:
      build: ./pyapp1
      container_name: flask1
      restart: always
      environment: 
        - APP_NAME=FlaskHello
      expose: 
        - 8080
    
    pyapp2:
      build: ./pyapp2
      container_name: flask2
      restart: always
      environment: 
        - APP_NAME=FlaskNameParser
      expose: 
        - 8080

    webserver:
      build: ./webserver
      container_name: multiwebserver
      restart: always
      ports: 
        - "80:80"