version: "3.7"

services:

    pyapp1:
      image: pyapp1
      build: .
      environment:
        - APP_NAME=FlaskHello
      expose:
        - 8080

    pyapp2:
      image: pyapp2
      build: .
      environment:
        - APP_NAME=FlaskNameParser
      expose:
        - 8080

    textspinner:
      image: textspinner
      build: .
      environment:
        - APP_NAME=FlaskTextSpinner
      expose:
        - 8080

    textspinner:
      image: addressparser
      build: .
      environment:
        - APP_NAME=FlaskAddressParser
      expose:
        - 8080

    webserver:
      image: webserver
      build: .
      ports:
        - "80:80"